# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import pdfuploader.validators
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='_Tagulous_Archive_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='PDFSuploads/%Y/%m/%d/', validators=[pdfuploader.validators.validate_file_ext], verbose_name='Archivo')),
                ('title', models.CharField(max_length=200, verbose_name='T\xedtulo')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora de subida')),
                ('creationdate', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creaci\xf3n')),
                ('uploader', models.TextField(blank=True, max_length=25, null=True, verbose_name='Usuario que lo sube.')),
                ('locked', models.BooleanField(default=False, verbose_name='Protegido por contrase\xf1a')),
                ('hash_data', models.TextField(max_length=250, unique=True, verbose_name='Hash')),
                ('author', models.TextField(blank=True, default='', help_text='Autor del pdf.', verbose_name='Autor')),
                ('produced_by', models.TextField(blank=True, default='', help_text='Software/compa\xf1\xeda que lo hizo.', verbose_name='Hecho con ')),
                ('url', models.URLField(blank=True, default='', help_text='Website relacionado con el archivo.', verbose_name='URL')),
                ('pages', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='P\xe1ginas')),
                ('size', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tama\xf1o')),
                ('isbn', models.TextField(blank=True, default='', max_length=15, verbose_name='ISBN')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=5, to='pdfuploader._Tagulous_Archive_tags', verbose_name='Etiquetas')),

            ],
            options={
                'verbose_name': 'Archivo',
            },
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_archive_tags',
            unique_together=set([('slug',)]),
        ),
    ]
