# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 09:24
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pdfuploader', '0003_auto_20170314_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Introduzca palabras separadas por coma', max_count=5, to='pdfuploader._Tagulous_Archive_tags', verbose_name='Etiquetas'),
        ),
    ]
