# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import pdfuploader.validators
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pdfuploader', '0005_auto_20170314_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='author',
            field=models.TextField(blank=True, default='', help_text='PDF author.', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='creationdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='creator',
            field=models.TextField(blank=True, default='', max_length=50, verbose_name='Other software used'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(upload_to='PDFSuploads/%Y/%m/%d/', validators=[pdfuploader.validators.validate_file_ext], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='isbn',
            field=models.TextField(blank=True, default='', max_length=15, verbose_name='Commercial code'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Password protected'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='produced_by',
            field=models.TextField(blank=True, default='', help_text='Software/company who made it.', verbose_name='Done by '),
        ),
        migrations.AlterField(
            model_name='archive',
            name='producer',
            field=models.TextField(blank=True, default='', max_length=50, verbose_name='Software used'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter comma separated words', max_count=5, to='pdfuploader._Tagulous_Archive_tags', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload date-time'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='uploader',
            field=models.TextField(blank=True, max_length=25, null=True, verbose_name='Uploading user'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Website', verbose_name='URL'),
        ),
    ]
