# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfuploader', '0006_auto_20170314_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name': 'Archives'},
        ),
    ]
