# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-31 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfuploader', '0007_auto_20170321_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='_Tagulous_Archive_tags',
            new_name='Tagulous_Archive_tags',
        ),
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name': 'archive', 'verbose_name_plural': 'archives'},
        ),
    ]
